=== zsomle99/hc1y8y_xmlgyak/XMLTASKHC1Y8Y/src/xmltaskHC1Y8Y/XMLSchemaHC1Y8Y.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="hibakezelés">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="hiba" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
              <xs:element type="xs:string" name="hibaüzenet"/>
              <xs:element name="időtartam">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="mióta"/>
                    <xs:element type="xs:nonNegativeInteger" name="hányszor"/>
                    <xs:element type="xs:nonNegativeInteger" name="hibaazon"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="tv">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:nonNegativeInteger" name="ügyfélazon"/>
                    <xs:element type="xs:nonNegativeInteger" name="hibaazon"/>
                    <xs:element type="xs:string" name="hibaidő"/>
                    <xs:element type="xs:string" name="gyakoriság"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="telefon">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:nonNegativeInteger" name="ügyfélazon"/>
                    <xs:element type="xs:nonNegativeInteger" name="hibaazon"/>
                    <xs:element type="xs:string" name="hibaidő"/>
                    <xs:element type="xs:string" name="gyakoriság"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="internet">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:nonNegativeInteger" name="ügyfélazon"/>
                    <xs:element type="xs:nonNegativeInteger" name="hibaazon"/>
                    <xs:element type="xs:string" name="hibaidő"/>
                    <xs:element type="xs:string" name="gyakoriság"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="email">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:nonNegativeInteger" name="ügyfélazon"/>
                    <xs:element type="xs:nonNegativeInteger" name="vezetőazon"/>
                  </xs:sequence>
                  <xs:attribute type="xs:nonNegativeInteger" name="id"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="levél">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:nonNegativeInteger" name="ügyfélazon" minOccurs="0"/>
                    <xs:element type="xs:nonNegativeInteger" name="ügyintézőazon" minOccurs="0"/>
                    <xs:element type="xs:nonNegativeInteger" name="vezetőazon"/>
                  </xs:sequence>
                  <xs:attribute type="xs:nonNegativeInteger" name="id" use="optional"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="ügyfél">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="szül_idő"/>
                    <xs:element type="xs:string" name="szül_hely"/>
                    <xs:element type="xs:nonNegativeInteger" name="kód"/>
                    <xs:element type="xs:string" name="név"/>
                  </xs:sequence>
                  <xs:attribute type="xs:nonNegativeInteger" name="üid" use="optional"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="ügyintéző">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:nonNegativeInteger" name="szint"/>
                    <xs:element type="xs:string" name="név"/>
                    <xs:element type="xs:string" name="beosztás"/>
                  </xs:sequence>
                  <xs:attribute type="xs:nonNegativeInteger" name="ügyid" use="optional"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="vezető">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="név"/>
                    <xs:element type="xs:string" name="beosztás"/>
                    <xs:element type="xs:nonNegativeInteger" name="szint"/>
                  </xs:sequence>
                  <xs:attribute type="xs:nonNegativeInteger" name="vid" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:choice>
            <xs:attribute type="xs:nonNegativeInteger" name="hid" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== zsomle99/hc1y8y_xmlgyak/DOMParseHC1Y8Y/XMLHC1Y8Y.xml
<?xml version="1.0" encoding="UTF-8"?>

<hibakezelés xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="http://www.example.com/XMLSchemaHC1Y8Y.xsd">
	<hiba hid="01">
		<hibaüzenet>TV hibaüzenet</hibaüzenet>
		<időtartam>
			<mióta>10:00</mióta>
			<hányszor>3</hányszor>
		</időtartam>
	
	
		<ügyfél üid="01">
			<szül_idő>1999.09.03</szül_idő>
			<szül_hely>Miskolc</szül_hely>
			<kód>14213456</kód>
			<név>XYZ</név>
		</ügyfél>
	
		<ügyintéző ügyid="01">
			<szint>3</szint>
			<név>LKP</név>
			<beosztás>operátor</beosztás>
		</ügyintéző>

		<vezető vid="01">
			<név>MKP</név>
			<beosztás>vezető operátor</beosztás>
			<szint>1</szint>
		</vezető>
	</hiba>
	
		<hiba hid="02">
		<hibaüzenet>Telefon hibaüzenet</hibaüzenet>
		<időtartam>
			<mióta>07:00</mióta>
			<hányszor>8</hányszor>
		</időtartam>
	
	
		<ügyfél üid="02">
			<szül_idő>2000.11.08</szül_idő>
			<szül_hely>Miskolc</szül_hely>
			<kód>76576523</kód>
			<név>PKZ</név>
		</ügyfél>
	
		<ügyintéző ügyid="02">
			<szint>2</szint>
			<név>WDT</név>
			<beosztás>operátor</beosztás>
		</ügyintéző>

		<vezető vid="02">
			<név>MIP</név>
			<beosztás>vezető helyettes operátor</beosztás>
			<szint>1</szint>
		</vezető>
	</hiba>
	
		<hiba hid="03">
		<hibaüzenet>Internet hibaüzenet</hibaüzenet>
		<időtartam>
			<mióta>13:00</mióta>
			<hányszor>5</hányszor>
		</időtartam>
	
	
		<ügyfél üid="03">
			<szül_idő>1999.03.21</szül_idő>
			<szül_hely>Miskolc</szül_hely>
			<kód>00243511</kód>
			<név>MNB</név>
		</ügyfél>
	
		<ügyintéző ügyid="03">
			<szint>3</szint>
			<név>MIN</név>
			<beosztás>operátor</beosztás>
		</ügyintéző>

		<vezető vid="03">
			<név>DOP</név>
			<beosztás>vezető operátor</beosztás>
			<szint>1</szint>
		</vezető>
	</hiba>
</hibakezelés>

=== zsomle99/hc1y8y_xmlgyak/XMLTASKHC1Y8Y/src/xmltaskHC1Y8Y/XMLHC1Y8Y.xml
<?xml version="1.0" encoding="UTF-8"?>

<hibakezelés xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="http://www.example.com/XMLSchemaHC1Y8Y.xsd">
	<hiba hid="01">
		<hibaüzenet>TV hibaüzenet</hibaüzenet>
		<időtartam>
			<hibaazon>1</hibaazon>
			<mióta>10:00</mióta>
			<hányszor>3</hányszor>
		</időtartam>
		
		<tv>
			<ügyfélazon>1</ügyfélazon>
			<hibaazon>1</hibaazon>
			<hibaidő>22 óra</hibaidő>
			<gyakoriság>gyakori</gyakoriság>
		</tv>
		
		<telefon>
			<ügyfélazon>2</ügyfélazon>
			<hibaazon>2</hibaazon>
			<hibaidő>1 óra</hibaidő>
			<gyakoriság>gyakori</gyakoriság>
		</telefon>
		
		<internet>
			<ügyfélazon>3</ügyfélazon>
			<hibaazon>3</hibaazon>
			<hibaidő>19 óra</hibaidő>
			<gyakoriság>gyakori</gyakoriság>
		</internet>
		
		<email id="1">
			<ügyfélazon>1</ügyfélazon>
			<vezetőazon>1</vezetőazon>
		</email>
		
		<levél>
			<ügyfélazon>2</ügyfélazon>
			<vezetőazon>2</vezetőazon>
		</levél>
		
		<email id="2">
			<ügyintézőazon>1</ügyintézőazon>
			<vezetőazon>3</vezetőazon>
		</email>
		
		<telefon id="1">
			<ügyintézőazon>2</ügyintézőazon>
			<vezetőazon>1</vezetőazon>
			<idő>
				<mettől>9:00</mettől>
				<meddig>10:00</meddig>
			</idő>
		</telefon>
		
		<telefon id="2">
			<ügyintézőazon>1</ügyintézőazon>
			<ügyfélazon>1</ügyfélazon>
			<idő>
				<mettől>10:00</mettől>
				<meddig>10:10</meddig>
			</idő>
		</telefon>
	
	
		<ügyfél üid="01">
			<szül_idő>1999.09.03</szül_idő>
			<szül_hely>Miskolc</szül_hely>
			<kód>14213456</kód>
			<név>XYZ</név>
		</ügyfél>
	
		<ügyintéző ügyid="01">
			<szint>3</szint>
			<név>LKP</név>
			<beosztás>operátor</beosztás>
		</ügyintéző>

		<vezető vid="01">
			<név>MKP</név>
			<beosztás>vezető operátor</beosztás>
			<szint>1</szint>
		</vezető>
	</hiba>
	
		<hiba hid="02">
		<hibaüzenet>Telefon hibaüzenet</hibaüzenet>
		<időtartam>
			<mióta>07:00</mióta>
			<hányszor>8</hányszor>
		</időtartam>
	
	
		<ügyfél üid="02">
			<szül_idő>2000.11.08</szül_idő>
			<szül_hely>Miskolc</szül_hely>
			<kód>76576523</kód>
			<név>PKZ</név>
		</ügyfél>
	
		<ügyintéző ügyid="02">
			<szint>2</szint>
			<név>WDT</név>
			<beosztás>operátor</beosztás>
		</ügyintéző>

		<vezető vid="02">
			<név>MIP</név>
			<beosztás>vezető helyettes operátor</beosztás>
			<szint>1</szint>
		</vezető>
	</hiba>
	
		<hiba hid="03">
		<hibaüzenet>Internet hibaüzenet</hibaüzenet>
		<időtartam>
			<mióta>13:00</mióta>
			<hányszor>5</hányszor>
		</időtartam>
	
	
		<ügyfél üid="03">
			<szül_idő>1999.03.21</szül_idő>
			<szül_hely>Miskolc</szül_hely>
			<kód>00243511</kód>
			<név>MNB</név>
		</ügyfél>
	
		<ügyintéző ügyid="03">
			<szint>3</szint>
			<név>MIN</név>
			<beosztás>operátor</beosztás>
		</ügyintéző>

		<vezető vid="03">
			<név>DOP</név>
			<beosztás>vezető operátor</beosztás>
			<szint>1</szint>
		</vezető>
	</hiba>
</hibakezelés>
